<%@ Page language="c#" Inherits="WebApplication2.frmUpdTask" CodeFile="frmUpdTask.aspx.cs" %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" >
<HTML>
	<HEAD>
		<title>frmAddProcedure</title>
		<meta content="Microsoft Visual Studio 7.0" name="GENERATOR">
		<meta content="C#" name="CODE_LANGUAGE">
		<meta content="JavaScript" name="vs_defaultClientScript">
		<meta content="http://schemas.microsoft.com/intellisense/ie5" name="vs_targetSchema">
	</HEAD>
	<body bgColor="white">
		<form id="frmAddProcedure" method="post" runat="server">
			<asp:label id="lblContent" style="Z-INDEX: 100; LEFT: 3px; POSITION: absolute; TOP: 45px" runat="server" Width="675px" Height="30px" Font-Size="Small" ForeColor="Navy"></asp:label>
			<asp:dropdownlist id="lstProcs" style="Z-INDEX: 120; LEFT: 845px; POSITION: absolute; TOP: 372px" runat="server" ForeColor="Navy" Height="25" Width="221px" Visible="False"></asp:dropdownlist>
			<asp:label id="Label5" style="Z-INDEX: 117; LEFT: 845px; POSITION: absolute; TOP: 340px" runat="server" ForeColor="Navy" Font-Size="Small" Height="23px" Width="221px" BorderStyle="None" BorderColor="Navy" Visible="False">Type of Task</asp:label>
			<asp:button id="btnLoc" style="Z-INDEX: 119; LEFT: 884px; POSITION: absolute; TOP: 205px" runat="server" ForeColor="White" Height="30px" Width="115px" Visible="False" Font-Bold="True" BackColor="Navy" BorderStyle="None" Text="Add Location" onclick="btnLoc_Click"></asp:button>
			<asp:button id="btnDetails" style="Z-INDEX: 118; LEFT: 509px; POSITION: absolute; TOP: 308px" runat="server" ForeColor="White" Height="48px" Width="152px" BorderStyle="None" BackColor="Maroon" Font-Bold="True" Visible="False" onclick="btnDetails_Click"></asp:button><asp:label id="lblLocs" style="Z-INDEX: 116; LEFT: 845px; POSITION: absolute; TOP: 266px" runat="server" Height="23px" Font-Size="Small" ForeColor="Navy" BorderStyle="None" BorderColor="Navy" Width="221px" Visible="False">Location</asp:label><asp:dropdownlist id="lstLocations" style="Z-INDEX: 114; LEFT: 845px; POSITION: absolute; TOP: 295px" runat="server" Width="221px" Height="25" ForeColor="Navy" Visible="False"></asp:dropdownlist><asp:label id="Label3" style="Z-INDEX: 113; LEFT: 415px; POSITION: absolute; TOP: 227px" runat="server" Width="101px" Height="23px" Font-Size="Small" ForeColor="Navy" BorderStyle="None" BorderColor="Navy" Visible="False">End Time</asp:label><asp:textbox id="txtEndTime" style="Z-INDEX: 112; LEFT: 532px; POSITION: absolute; TOP: 225px" runat="server" Width="185px" Height="28px" ForeColor="Navy" BorderStyle="Solid" BackColor="White" Visible="False"></asp:textbox><asp:label id="Label2" style="Z-INDEX: 111; LEFT: 409px; POSITION: absolute; TOP: 181px" runat="server" Width="101px" Height="21px" Font-Size="Small" ForeColor="Navy" BorderStyle="None" BorderColor="Navy" Visible="False"> Start Time</asp:label><asp:textbox id="txtStartTime" style="Z-INDEX: 110; LEFT: 532px; POSITION: absolute; TOP: 176px" runat="server" Width="185px" Height="28px" ForeColor="Navy" BorderStyle="Solid" BackColor="White" Visible="False"></asp:textbox><asp:label id="Label1" style="Z-INDEX: 109; LEFT: 96px; POSITION: absolute; TOP: 172px" runat="server" Width="65px" Height="23px" Font-Size="Small" ForeColor="Navy" BorderStyle="None" BorderColor="Navy"> Status</asp:label><asp:radiobuttonlist id="rblStatus" style="Z-INDEX: 108; LEFT: 174px; POSITION: absolute; TOP: 176px" runat="server" Width="146px" Font-Size="Small" ForeColor="Navy" BorderStyle="Solid" BorderColor="Navy" BorderWidth="2px">
				<asp:ListItem Value="Planned">Planned</asp:ListItem>
				<asp:ListItem Value="Open" Selected="True">Open</asp:ListItem>
				<asp:ListItem Value="Closed">Closed</asp:ListItem>
				<asp:ListItem Value="Cancelled">Cancelled</asp:ListItem>
			</asp:radiobuttonlist><asp:button id="btnCancel" style="Z-INDEX: 107; LEFT: 343px; POSITION: absolute; TOP: 310px" runat="server" Width="152px" Height="48px" ForeColor="White" BorderStyle="None" BackColor="Maroon" Text="Cancel" Font-Bold="True" onclick="btnCancel_Click"></asp:button><asp:label id="lblOrg" style="Z-INDEX: 106; LEFT: 3px; POSITION: absolute; TOP: 4px" runat="server" Width="914px" Height="30px" Font-Size="Small" ForeColor="Navy" Font-Bold="True"></asp:label><asp:label id="lblProcName" style="Z-INDEX: 104; LEFT: 102px; POSITION: absolute; TOP: 113px" runat="server" Width="62px" Height="40px" Font-Size="Small" ForeColor="Navy" BorderStyle="None" BorderColor="Navy"> Name</asp:label><asp:textbox id="txtName" style="Z-INDEX: 101; LEFT: 175px; POSITION: absolute; TOP: 114px" runat="server" Width="545px" Height="36px" ForeColor="Navy" BorderStyle="Solid" BorderColor="Navy" BackColor="White"></asp:textbox><asp:button id="btnAction" style="Z-INDEX: 103; LEFT: 177px; POSITION: absolute; TOP: 309px" runat="server" Width="152px" Height="48px" ForeColor="White" BorderStyle="None" BackColor="Maroon" Text="Action" Font-Bold="True" onclick="btnAction_Click"></asp:button></form>
	</body>
</HTML>
